stages:
  - build
  - build-deploy

build:
  stage: build
  only:
    - main
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"

build-deploy:
  stage: build-deploy
  image: kroniak/ssh-client
  only:
    - feat/CI-GitLab
  before_script:
    - echo $SSH_PRIVATE_KEY
    - echo "Deploying app"
  script:
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "rm -rf /public/pre-freshy-2021-frontend/.env.local /public/pre-freshy-2021-frontend/Dockerfile"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "cd /public/pre-freshy-2021-frontend/ && git pull"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "cp /public/env/.env.local /public/pre-freshy-2021-frontend/.env.local"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "cp /public/env/Dockerfile /public/pre-freshy-2021-frontend/Dockerfile"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "cd /public/pre-freshy-2021-frontend/ docker build --pull -t $CI_REGISTRY_IMAGE ."
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "docker push $CI_REGISTRY_IMAGE"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "docker stop PreFreshy2021 || true && docker rm PreFreshy2021 || true"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$PROD_SERVER_IP "docker run -p 8000:3000 -d --name PreFreshy2021 $CI_REGISTRY_IMAGE"

